### ISSUE TITLE
[BUG] [SERVER/EXTENSION] - TITLE

### ISSUE THREAD

**Issue by sriramsvenkat** [Static-Flow/BurpSuite-Team-Extension#5]
When I try to load the JAR file from the build folder, I see this error message:

java.lang.UnsupportedClassVersionError: burp/BurpExtender has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at burp.acu.a(Unknown Source)
	at burp.acu.<init>(Unknown Source)
	at burp.m.a(Unknown Source)
	at burp.ey9.lambda$panelLoaded$0(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
The extension could not be loaded because it requires a later version of Java. To use this extension you will need to start Burp with the required or later Java version.

**NOTE: I encounter the same issue with JRE (Version 8 Update 221) and even tried installing JDK 11, 12, 13**

**Comment by Static-Flow** [comment]
This is fixed with version 2.0

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
