### ISSUE TITLE
[BUG] Extension not loading on Burp 2.1.07

### ISSUE THREAD

**Issue by ghost** [Static-Flow/BurpSuite-Team-Extension#9]
I can't start client extension on Burp Suite Professional 2.1.07

`
java.lang.RuntimeException: java.lang.NoClassDefFoundError: teamextension/ServerListCustomCellRenderer
	at burp.bvn.a(Unknown Source)
	at burp.ez1.addSuiteTab(Unknown Source)
	at burp.apo.addSuiteTab(Unknown Source)
	at burp.bho.addSuiteTab(Unknown Source)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at burp.elf.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
java.lang.RuntimeException: java.lang.NoClassDefFoundError: teamextension/ServerListCustomCellRenderer
	at burp.bvn.a(Unknown Source)
	at burp.ez1.addSuiteTab(Unknown Source)
	at burp.apo.addSuiteTab(Unknown Source)
	at burp.bho.addSuiteTab(Unknown Source)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at burp.elf.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
`

 - OS: macOS 10.15.2
 - Burp Version: 2.1.07

**Comment by Static-Flow** [comment]
Are you building it yourself or using the jar located at "/BurpSuite-Team-Extension/target/BurpSuiteCollaborationClient.jar". I just pulled it down and loaded the jar which worked for me. I am on macOS 10.14.7 and the same Burp. I was also able to compile it using this version of Java:

openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

**Comment by ghost** [comment]
when I load the one in repository "/target/BurpSuiteCollaborationClient.jar" I get this error instead:

`
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:415)
	at burp.elf.a(Unknown Source)
	at burp.elf.<init>(Unknown Source)
	at burp.c7u.a(Unknown Source)
	at burp.fuj.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
`

I was compiling it with maven but I have Java / JDK 13.0.1 installed with brew:

`
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3/libexec
Java version: 13.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.2", arch: "x86_64", family: "mac"
`

Should I switch to Java / JDK 12 with brew install or the fact that burp uses a bundled version of java 12 is enough?

**Comment by Static-Flow** [comment]
The weird part is it's saying it can't find Burp

**Comment by Static-Flow** [comment]
It's odd that both the errors have to do with not finding classes which suggests a classpath issue. Maven should handle all of that for you. Java 12 vs 13 _shouldn't_ matter but it might be worth trying to compile on 12. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Static-Flow** [comment]
I'll try and compile it on a fresh system to rule out any "works on my machine" issues

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ghost** [comment]
I just downloaded the jar in repository again and now it's loading just fine 👍 

Thank You

**Comment by Static-Flow** [comment]
Glad I could rubber duck debug for you 😂 lemme know if there are any other issues!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
